name: Build & Push Image on Tag

on:
  pull_request:
    branches: [ main ]
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      # 1. BUILD ONLY (Runs on Pull Requests)
      # This verifies that the Docker image builds correctly without trying to push.
      - name: Build Image (Test only)
        if: github.event_name == 'pull_request'
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          ./gradlew build \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.registry=${{ secrets.HARBOR_REGISTRY }} \
            -Dquarkus.container-image.group=${{ secrets.HARBOR_PROJECT }} \
            -Dquarkus.container-image.tag=$VERSION \
            -Dquarkus.container-image.additional-tags=latest

      # #./gradlew build -Dquarkus.container-image.build=true

      # 2. BUILD & PUSH (Runs only on Tags)
      # This performs the actual deployment to Harbor.
      - name: Build and Push Image to Harbor
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          ./gradlew build \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.registry=${{ secrets.HARBOR_REGISTRY }} \
            -Dquarkus.container-image.group=${{ secrets.HARBOR_PROJECT }} \
            -Dquarkus.container-image.tag=$VERSION \
            -Dquarkus.container-image.additional-tags=latest
